config/routes.rb
Rails.application.routes.draw do
  resources :searches

root to: "searches#index"
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @search = Search.new
    @searches = Search.all
  end

  def create
    @search = Search.new(search_params)
    if @search.save
      redirect_to :back, notice: 'Search was successfully created.'
    else
      render :index, notice: 'Search was unsuccessfully created.'
    end
  end
  private

  def search_params
    params.require(:search).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventful Event Map</title>
  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
  <script src="dist/datamaps.usa.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-ng-app="app">
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="color: #ff80ff">Eventful Event Map</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><a href="https://github.com/csmartinez/Eventful-U.S.-Map" target="_blank">Github<span class="sr-only">(current)</span></a></li>
        <li><a href="http://eventful.com" target="_blank">Eventful.com</a></li>
      </ul>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/searches/index.html.erb
<div class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <%= form_for @search, url: searches_path, html: {class: "search-form", :multipart => true} do |f| %>
              <%= f.label :Search_Keyword_ %> <%= f.text_field :name %>
          </div>
          <%= f.submit 'Submit', :class => "btn btn-primary" %>
      <% end %>
    </div>
      <ul class="nav navbar-nav navbar-right">
      <li data-toggle="modal" data-target="#myModal"><a>About</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="margin-top: 180px">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h3 class="modal-title" id="myModalLabel" style="color: #ff80ff">Eventful Event Map <small>by Carli Martinez</small></h3>
            </div>
            <div class="modal-body">
              <p>Search a keyword (a musician, genre, dog show, comedian, etc.) and view how many events related
                to that keyword are in each American state. Uses <a href="http://api.eventful.com/libs/ruby/doc/index.html">
                  Ruby Eventful API</a>, D3.js, <a href="http://datamaps.github.io">datamaps</a> by markmarkoh,
                Topjson, and a <a href="https://bootswatch.com/lumen/">Lumen</a> Bootswatch.<br><br>

                Please note it's slow due to searches made individually by each state. More functionality
                to come...stay tuned.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" data-dismiss="modal">Okay</button>
            </div>
          </div>
        </div>
      </div>

<% arr = [] %>

<% @searches.each do |search| %>
<% arr = [] %>
<% arr.push(search.name) %>
<% end %>

<h1><%= keyword = arr[-1].to_s %></h1>
<%
 require 'rubygems'
 require 'eventful/api'

 # First, create our Eventful::API object
 eventful = Eventful::API.new '8WnSwHfBrTmGP4mj'
 nation_events = []
 nation_total = []
 states = ["Arizona0", "California1", "Oregon2", "Washington3", "Nevada4", "Idaho5","Montana6",
            "NewMexico7", "Texas8", "Missouri9", "Utah10", "Colorado11" ]

   states.each do |state|
     state_events = []
     result = " "
     results = eventful.call 'events/search',
                             :keywords => keyword,
                             :location => state,
                             :date => "Future",
                             :page_number => 1

     if results['events'].nil? then
       result += "Hmm. I couldn't find anything. Sorry."
     else

     nation_total.push(results['total_items'])
     counter = 0
     # Output the results
     while counter <= 1 do
        results['events']['event'].each do |event|
            counter += 1
            state_events.push(result)
          end
        nation_events.push(state_events)
      end
   end
  end
 %>
<% state_color_arr = []%>

<% nation_total.each do |state| %>
  <% if state.to_i > 100 %>
    <% state_color_arr.push("Heavy") %>
  <% elsif state.to_i > 40 %>
    <% state_color_arr.push("Medium") %>
  <% else %>
    <% state_color_arr.push("Low")%>
  <% end %>
<% end %>

<div id="container" style="position: relative; width: 1000px; height: 600px;"></div>

<script>
    var map = new Datamap({
        element: document.getElementById('container'),
        scope: 'usa',
        done: function(datamap) {
            datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
              var div = document.getElementById("info");
              if (div.style.display !== 'none') {
                  div.style.display = 'none';
              }
              else {
                  div.style.display = 'block';
              }
            });
        },
        geographyConfig: {
        highlightBorderColor: '#937B76',
        highlightFillColor: '#A28F8B',
       popupTemplate: function(geography, data) {
          return '<div ng-click="myFunc()" class="hoverinfo">' + data.events +
          ''
        },
        highlightBorderWidth: 3
      },
        fills: {
        "Low": '#ffb3ff',
        'Medium': '#ff80ff',
        'Heavy': '#ff1aff',
        defaultFill: '#ffe6ff'
      },
      data:{
      "AZ": {
          "fillKey": "<%= state_color_arr[0].to_s %>",
          "events": "<%= nation_total[0] %>" + " Events",
          "state": "AZ"
      },
      "CO": {
        "fillKey": "<%= state_color_arr[11].to_s %>",
        "events": "<%= nation_total[11] %>" + " Events",
        "state": "CO"
      },
      "DE": {
        "fillKey": "<%= state_color_arr[22].to_s %>",
        "events": "<%= nation_total[22] %>" + " Events",
        "state": "DE"
      },
      "FL": {
        "fillKey": "<%= state_color_arr[18].to_s %>",
        "events": "<%= nation_total[18] %>" + " Events"
      },
      "GA": {
        "fillKey": "<%= state_color_arr[24].to_s %>",
        "events": "<%= nation_total[24] %>" + " Events"
      },
      "HI": {
        "fillKey": "<%= state_color_arr[25].to_s %>",
        "events": "<%= nation_total[25] %>" + " Events"
      },
      "ID": {
        "fillKey": "<%= state_color_arr[5].to_s %>",
        "events": "<%= nation_total[5] %>" + " Events"
      },
      "IL": {
        "fillKey": "<%= state_color_arr[15].to_s %>",
        "events": "<%= nation_total[15] %>" + " Events"
      },
      "IN": {
        "fillKey": "<%= state_color_arr[16].to_s %>",
        "events": "<%= nation_total[16] %>" + " Events"
      },
      "IA": {
        "fillKey": "<%= state_color_arr[28].to_s %>",
        "events": "<%= nation_total[28] %>" + " Events"
      },
      "KS": {
        "fillKey": "<%= state_color_arr[23].to_s %>",
        "events": "<%= nation_total[23] %>" + " Events"
      },
      "KY": {
        "fillKey": "<%= state_color_arr[19].to_s %>",
        "events": "<%= nation_total[19] %>" + " Events"
      },
      "LA": {
        "fillKey": "<%= state_color_arr[20].to_s %>",
        "events": "<%= nation_total[20] %>" + " Events"
      },
      "MD": {
        "fillKey": "<%= state_color_arr[21].to_s %>",
        "events": "<%= nation_total[21] %>" + " Events"
      },
      "ME": {
        "fillKey": "<%= state_color_arr[30].to_s %>",
        "events": "<%= nation_total[30] %>" + " Events"
      },
      "MA": {
        "fillKey": "<%= state_color_arr[26].to_s %>",
        "events": "<%= nation_total[26] %>" + " Events"
      },
      "MN": {
        "fillKey": "<%= state_color_arr[12].to_s %>",
        "events": "<%= nation_total[12] %>" + " Events"
      },
      "MI": {
        "fillKey": "<%= state_color_arr[14].to_s %>",
        "events": "<%= nation_total[14] %>" + " Events"
      },
      "MS": {
        "fillKey": "<%= state_color_arr[29].to_s %>",
        "events": "<%= nation_total[29] %>" + " Events"
      },
      "MO": {
        "fillKey": "<%= state_color_arr[9].to_s %>",
        "events": "<%= nation_total[9] %>" + " Events"
      },
      "MT": {
        "fillKey": "<%= state_color_arr[6].to_s %>",
        "events": "<%= nation_total[6] %>" + " Events"
      },
      "NC": {
        "fillKey": "<%= state_color_arr[31].to_s %>",
        "events": "<%= nation_total[31] %>" + " Events"
      },
      "NE": {
        "fillKey": "<%= state_color_arr[32].to_s %>",
        "events": "<%= nation_total[32] %>" + " Events"
      },
      "NV": {
        "fillKey": "<%= state_color_arr[4].to_s %>",
        "events": "<%= nation_total[4] %>" + " Events"
      },
      "NH": {
        "fillKey": "<%= state_color_arr[33].to_s %>",
        "events": "<%= nation_total[33] %>" + " Events"
      },
      "NJ": {
        "fillKey": "<%= state_color_arr[35].to_s %>",
        "events": "<%= nation_total[35] %>" + " Events"
      },
      "NY": {
        "fillKey": "<%= state_color_arr[17].to_s %>",
        "events": "<%= nation_total[17] %>" + " Events"
      },
      "ND": {
        "fillKey": "<%= state_color_arr[34].to_s %>",
        "events": "<%= nation_total[34] %>" + " Events"
      },
      "NM": {
        "fillKey": "<%= state_color_arr[7].to_s %>",
        "events": "<%= nation_total[7] %>" + " Events"
      },
      "OH": {
        "fillKey": "<%= state_color_arr[36].to_s %>",
        "events": "<%= nation_total[36] %>" + " Events"
      },
      "OK": {
        "fillKey": "<%= state_color_arr[37].to_s %>",
        "events": "<%= nation_total[37] %>" + " Events"
      },
      "OR": {
          "fillKey": "<%= state_color_arr[2] %>",
          "events": "<%= nation_total[2] %>" + " Events"
      },
      "PA": {
        "fillKey": "<%= state_color_arr[38].to_s %>",
        "events": "<%= nation_total[38] %>" + " Events"
      },
      "RI": {
        "fillKey": "<%= state_color_arr[39].to_s %>",
        "events": "<%= nation_total[39] %>" + " Events"
      },
      "SC": {
        "fillKey": "<%= state_color_arr[40].to_s %>",
        "events": "<%= nation_total[40] %>" + " Events"
      },
      "SD": {
        "fillKey": "<%= state_color_arr[41].to_s %>",
        "events": "<%= nation_total[41] %>" + " Events"
      },
      "TN": {
        "fillKey": "<%= state_color_arr[27].to_s %>",
        "events": "<%= nation_total[27] %>" + " Events"
      },
      "TX": {
        "fillKey": "<%= state_color_arr[8].to_s %>",
        "events": "<%= nation_total[8] %>" + " Events"
      },
      "UT": {
        "fillKey": "<%= state_color_arr[10].to_s %>",
        "events": "<%= nation_total[10] %>" + " Events"
      },
      "WI": {
        "fillKey": "<%= state_color_arr[42].to_s %>",
        "events": "<%= nation_total[42] %>" + " Events"
      },
      "VA": {
        "fillKey": "<%= state_color_arr[43].to_s %>",
        "events": "<%= nation_total[43] %>" + " Events"
      },
      "VT": {
        "fillKey": "<%= state_color_arr[44].to_s %>",
        "events": "<%= nation_total[44] %>" + " Events"
      },
      "WA": {
          "fillKey": "<%= state_color_arr[3] %>",
          "events": "<%= nation_total[3] %>" + " Events"
      },
      "WV": {
        "fillKey": "<%= state_color_arr[45] %>",
        "events": "<%= nation_total[45] %>" + " Events"
      },
      "WY": {
        "fillKey": "<%= state_color_arr[13] %>",
        "events": "<%= nation_total[13] %>"  + " Events"
      },
      "CA": {
          "fillKey": "<%= state_color_arr[1] %>",
          "events": "<%= nation_total[1] %>"  + " Events"
      },
      "CT": {
        "fillKey": "<%= state_color_arr[46] %>",
        "events": "<%= nation_total[46] %>"  + " Events"
      },
      "AK": {
        "fillKey": "<%= state_color_arr[47] %>",
        "events": "<%= nation_total[47] %>"  + " Events"
      },
      "AR": {
        "fillKey": "<%= state_color_arr[48] %>",
        "events": "<%= nation_total[48] %>"  + " Events"
      },
      "AL": {
        "fillKey": "<%= state_color_arr[49] %>",
        "events": "<%= nation_total[49] %>"  + " Events"
      }
      }
    });
</script>

<!-- <div ng-app="myApp" ng-controller="myCtrl">

<button ng-click="myFunc()">Click Me!</button>

<div ng-show="showMe">
    <h1>Menu:</h1>
    <div>Pizza</div>
    <div>Pasta</div>
    <div>Pesce</div>
</div>

</div>
<script>
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope) {
    $scope.showMe = false;
    $scope.myFunc = function() {
        $scope.showMe = !$scope.showMe;
    }
});
</script> -->

<div id="info"  style="display:none;" class="answer_list" >
<p>AZ yoooo</p><script>document.write(MyApp.color)</script>
</div>